# This file was generated by GoReleaser. DO NOT EDIT.
cask "closedsspm" do
  name "closedsspm"
  desc "Open Source SaaS Security Posture Management — audit SaaS platforms for security misconfigurations."
  homepage "https://github.com/PiotrMackowski/ClosedSSPM"
  version "0.3.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "closedsspm"
  binary "closedsspm-mcp"

  on_macos do
    on_intel do
      url "https://github.com/PiotrMackowski/ClosedSSPM/releases/download/v#{version}/closedsspm_#{version}_darwin_amd64.tar.gz"
      sha256 "002cb3850fa8f687b9c6fa721bd63eea7178606e46796a40c0b7a390bf2b87f0"
    end
    on_arm do
      url "https://github.com/PiotrMackowski/ClosedSSPM/releases/download/v#{version}/closedsspm_#{version}_darwin_arm64.tar.gz"
      sha256 "5f57e595d3bd1990a33c6a26fe3a21a11f30888d139d08be89c40e27af1d1d8e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/PiotrMackowski/ClosedSSPM/releases/download/v#{version}/closedsspm_#{version}_linux_amd64.tar.gz"
      sha256 "e6aa2f1172ca979003fac951c386d807e8d42184848a706bdfb42cfa77943bfc"
    end
    on_arm do
      url "https://github.com/PiotrMackowski/ClosedSSPM/releases/download/v#{version}/closedsspm_#{version}_linux_arm64.tar.gz"
      sha256 "f01e4f55310e8d39390b42e695fcaa5c644e1ff01fd8f2b3a014bf0493888fdd"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/closedsspm"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/closedsspm-mcp"]
    end
  end

  # No zap stanza required
end
