# This file was generated by GoReleaser. DO NOT EDIT.
cask "closedsspm" do
  name "closedsspm"
  desc "Open Source SaaS Security Posture Management — audit SaaS platforms for security misconfigurations."
  homepage "https://github.com/PiotrMackowski/ClosedSSPM"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "closedsspm"
  binary "closedsspm-mcp"

  on_macos do
    on_intel do
      url "https://github.com/PiotrMackowski/ClosedSSPM/releases/download/v#{version}/closedsspm_#{version}_darwin_amd64.tar.gz"
      sha256 "4c41cfa0aaf47b3dd2aa18b90f659a1d943e39d98fbe9119f17a0e5632831a07"
    end
    on_arm do
      url "https://github.com/PiotrMackowski/ClosedSSPM/releases/download/v#{version}/closedsspm_#{version}_darwin_arm64.tar.gz"
      sha256 "802cc3a0c712dcf756d9242fb5a163c970f045857a73974c5421bece2608ac21"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/PiotrMackowski/ClosedSSPM/releases/download/v#{version}/closedsspm_#{version}_linux_amd64.tar.gz"
      sha256 "46a95e58953325afe7d2f0560a9b7b11cfc8bc7130233664acf48f753f4d2b43"
    end
    on_arm do
      url "https://github.com/PiotrMackowski/ClosedSSPM/releases/download/v#{version}/closedsspm_#{version}_linux_arm64.tar.gz"
      sha256 "2b995bb3a2c179cd9629234d1dae813c1b4ebb24c0dab20ed4986d6235618329"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/closedsspm"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/closedsspm-mcp"]
    end
  end

  # No zap stanza required
end
