# This file was generated by GoReleaser. DO NOT EDIT.
cask "closedsspm" do
  version "0.4.2"

  on_macos do
    on_intel do
      sha256 "915c68077ca56095a4cb79e77397b6a28b5e6e0109bd251d8baa73e30fbb7a42"
      url "https://github.com/PiotrMackowski/ClosedSSPM/releases/download/v#{version}/closedsspm_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5dc904f71c91f230787366ad8d61d8904ed563a1865395754e075fc4d16587df"
      url "https://github.com/PiotrMackowski/ClosedSSPM/releases/download/v#{version}/closedsspm_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9f15b8d775e171bcdc0c8360098a4187e0cd732012553e49cc4f5fb8dc47f4f8"
      url "https://github.com/PiotrMackowski/ClosedSSPM/releases/download/v#{version}/closedsspm_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e26f7e14546c52a603770bc3d3b12639b7a91694dcf3cc45a23b8c69e43fdd66"
      url "https://github.com/PiotrMackowski/ClosedSSPM/releases/download/v#{version}/closedsspm_#{version}_linux_arm64.tar.gz"
    end
  end

  name "closedsspm"
  desc "Open Source SaaS Security Posture Management — audit SaaS platforms for security misconfigurations."
  homepage "https://github.com/PiotrMackowski/ClosedSSPM"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "closedsspm"
  binary "closedsspm-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/closedsspm"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/closedsspm-mcp"]
    end
  end

  # No zap stanza required

end
